repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # - id: trailing-whitespace
      # - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=10240'] # 10 MB
        exclude: '(^Library/|^Temp/|^Build/|^Logs/|^UserSettings/|\.unitypackage$)'
        stages: [pre-commit]
  # - repo: local
  #   hooks:
  #     - id: dotnet-format
  #       name: dotnet-format
  #       entry: dotnet
  #       args: ["format"]
  #       language: system
  #       pass_filenames: false
  #       stages: [pre-commit]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        args: [--strict, --force-scope]
        stages: [commit-msg]

