repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # - id: trailing-whitespace
      # - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=102400'] # 100 MiB
        exclude: '(^Library/|^Temp/|^Build/|^Logs/|^UserSettings/|\.unitypackage$)'
        stages: [pre-commit]
  # Setting up this hook is much more difficult then I thought.
  # Let's not do it for now or watch some tutorial.
  #
  # - repo: local
  #   hooks:
  #     - id: dotnet-format
  #       name: dotnet-format
  #       entry: dotnet
  #       args: ["format", "./2025_11c_02_6week.sln"]
  #       language: system
  #       pass_filenames: false
  #       stages: [pre-commit]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        args: [--strict, --force-scope]
        stages: [commit-msg]

